name: Build
on: workflow_dispatch
jobs:
  build_on_linux:
    runs-on: ubuntu-latest
    steps:
      - name: git clone code
        run: git clone git@github.com:xcxuehaiyang/GitAction_Demo.git
      - name: show codes
        run: ls -a
      - name: build
        run: gcc main.c -o hello
      - name: run
        run: ./hello
